export const BOOK_SESSION_REQUEST = "BOOK_SESSION_REQUEST";
export const BOOK_SESSION_SUCCESS = "BOOK_SESSION_SUCCESS";
export const BOOK_SESSION_FAIL = "BOOK_SESSION_FAIL";

export const BOOK_SESSION_RESET = "BOOK_SESSION_RESET";