export const EZ_KARO_FORM_REQUEST = "EZ_KARO_FORM_REQUEST";
export const EZ_KARO_FORM_SUCCESS = "EZ_KARO_FORM_SUCCESS";
export const EZ_KARO_FORM_FAIL = "EZ_KARO_FORM_FAIL";

export const GET_EZ_KARO_FORM_REQUEST = "GET_EZ_KARO_FORM_REQUEST";
export const GET_EZ_KARO_FORM_SUCCESS = "GET_EZ_KARO_FORM_SUCCESS";
export const GET_EZ_KARO_FORM_FAIL = "GET_EZ_KARO_FORM_FAIL";

export const GET_EZ_JOB_ROLES = "GET_EZ_JOB_ROLES";
export const GET_EZ_JOB_SKILLS = "GET_EZ_JOB_SKILLS";
export const GET_EZ_COMPANIES = "GET_EZ_COMPANIES";
export const GET_EZ_CATEGORIES = "GET_EZ_CATEGORIES";

export const CLEAR_PREVIOUS_STATE = "CLEAR_PREVIOUS_STATE";

export const CLEAR_EZ_ERRORS = "CLEAR_EZ_ERRORS";