export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";
export const CLEAR_COMMENT = "CLEAR_COMMENT";

export const ADD_UPVOTE_REQUEST = "ADD_UPVOTE_REQUEST";
export const ADD_UPVOTE_SUCCESS = "ADD_UPVOTE_SUCCESS";
export const ADD_UPVOTE_FAIL = "ADD_UPVOTE_FAIL";

export const REMOVE_UPVOTE_REQUEST = "REMOVE_UPVOTE_REQUEST";
export const REMOVE_UPVOTE_SUCCESS = "REMOVE_UPVOTE_SUCCESS";
export const REMOVE_UPVOTE_FAIL = "REMOVE_UPVOTE_FAIL";