export const SELLER_REGISTER_REQUEST = "SELLER_REGISTER_REQUEST";
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS";
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL";

export const CREATE_CATELOGUE_REQUEST = "CREATE_CATELOGUE_REQUEST";
export const CREATE_CATELOGUE_SUCCESS = "CREATE_CATELOGUE_SUCCESS";
export const CREATE_CATELOGUE_FAIL = "CREATE_CATELOGUE_FAIL";
export const CLEAR_CATALOG_SUCCESS = "CLEAR_CATALOG_SUCCESS";

export const ALL_SERVICES_LOAD_REQUEST = "ALL_SERVICES_LOAD_REQUEST";
export const ALL_SERVICES_LOAD_SUCCESS = "ALL_SERVICES_LOAD_SUCCESS";
export const ALL_SERVICES_LOAD_FAIL = "ALL_SERVICES_LOAD_FAIL";

export const ONE_SERVICE_LOAD_REQUEST = "ONE_SERVICE_LOAD_REQUEST";
export const ONE_SERVICE_LOAD_SUCCESS = "ONE_SERVICE_LOAD_SUCCESS";
export const ONE_SERVICE_LOAD_FAIL = "ONE_SERVICE_LOAD_FAIL";

export const SERVICE_TYPE_LOAD_REQUEST = "SERVICE_TYPE_LOAD_REQUEST";
export const SERVICE_TYPE_LOAD_SUCCESS = "SERVICE_TYPE_LOAD_SUCCESS";
export const SERVICE_TYPE_LOAD_FAIL = "SERVICE_TYPE_LOAD_FAIL";

export const SELLER_PROFILE_REQUEST = "SELLER_PROFILE_REQUEST";
export const SELLER_PROFILE_SUCCESS = "SELLER_PROFILE_SUCCESS";
export const SELLER_PROFILE_FAIL = "SELLER_PROFILE_FAIL";

export const SELLER_CATALOG_REQUEST = "SELLER_CATALOG_REQUEST";
export const SELLER_CATALOG_SUCCESS = "SELLER_CATALOG_SUCCESS";
export const SELLER_CATALOG_FAIL = "SELLER_CATALOG_FAIL";

export const INDIVIDUAL_CATALOG_REQUEST = "INDIVIDUAL_CATALOG_REQUEST";
export const INDIVIDUAL_CATALOG_SUCCESS = "INDIVIDUAL_CATALOG_SUCCESS";
export const INDIVIDUAL_CATALOG_FAIL = "INDIVIDUAL_CATALOG_FAIL";

export const FETCH_BOOKINGS_REQUEST = "FETCH_BOOKINGS_REQUEST";
export const FETCH_BOOKINGS_SUCCESS = "FETCH_BOOKINGS_SUCCESS";
export const FETCH_BOOKINGS_FAIL = "FETCH_BOOKINGS_FAIL";

export const SET_AVAILABILITY_REQUEST = "SET_AVAILABILITY_REQUEST";
export const SET_AVAILABILITY_SUCCESS = "SET_AVAILABILITY_SUCCESS";
export const SET_AVAILABILITY_FAIL = "SET_AVAILABILITY_FAIL";

export const CLEAR_SELLER_ERRORS = "CLEAR_SELLER_ERRORS";
